### ISSUE TITLE
Move entities to external data files

### ISSUE THREAD

**Issue by vkczyz** [OuseWorks/PiazzaPanic#10]
Instead of hard-coding entities in the `EntityFactory`, create external files (XML, JSON, or other) describing each entity and its components.

E.g.

```
<chef1>
    <position>
        <x>10</x>
        <y>10</y>
    </position>
    <sprite>
        <path>chef1.png</path>
    </sprite>
    ...
</chef1>
```

```
{
    name: "Chef1",
    components: [
        {
            "name": "Sprite",
            "path": "chef1.png"
        },
        {
            "name": "Position",
            "x": 10,
            "y": 10
        },
        ...
    ]
}

**Comment by ben260** [comment]
I've improved my original functions in the entity factory by including a general method to create a cook and specify its location and sprite. Then a game controller can create cooks using this method when the game is started.

**Comment by vkczyz** [comment]
Probably going to pass on this after all
